config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :public do
    get "home/about" => "homes#about"
    get "/search", to: "searches#search"
    resources :books, only: %i[index edit show create destroy update] do
      resources :book_comments, only: %i[create destroy]
      resource :favorites, only: %i[create destroy]
    end
    resources :customers, only: %i[index edit show update] do
      resource :relationships, only: %i[create destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      get "daily_posts" => "customers#daily_posts"
      patch :release
      patch :nonrelease
      get :unsubscribe
      patch :withdrawal
      member do
        get :likes
      end
    end
    resources :groups, only: %i[new index show create edit update destroy] do
      resource :group_customers, only: %i[create destroy]
      resources :event_notices, only: %i[new create]
      get "event_notices" => "event_notices#sent"
    end
    resources :chats, only: %i[show create]
    resources :ratings, only: %i[index create destroy]
    resources :notifications, only: [:index]
    resources :dictionaries, only: [:index] do
      collection do
        get :sns
        get :room
        get :user
        get :chat
      end
    end
  end

  scope module: :public do
    root to: "homes#top"
  end

  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post "customer/guest_sign_in", to: "customers/sessions#guest_sign_in"
  end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div id="error_explanation">
        <h3><%= pluralize(obj.errors.count, "件の") %>エラーが発生しました。</h3>
        <ul>
            <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="position-relative">
<div class="navbar navbar-expand-lg navbar-expand-md navbar-expand-sm navbar-light bg-info text-light position-absolute bottom-0 w-100 bg-dark">
    <div class="container d-flex flex-column">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <h1>CopyRight RNrd00</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
            <h2 style="text-align: center;">シェアしませんか？</h2>
            <ul class="navbar-nav" style="text-align: center;">
                <li>
                <%=link_to 'https://twitter.com/?lang=ja', class: 'nav-link text-light' do%>
                    <i class="fab fa-twitter display-2"></i>
                <%end%>
                </li>
                <li>
                <%=link_to 'https://www.instagram.com/', class: 'nav-link text-light' do%>
                    <i class="fab fa-instagram display-2"></i>
                <%end%>
                </li>
                <li>
                <%=link_to 'https://ja-jp.facebook.com/', class: 'nav-link text-light' do%>
                    <i class="fab fa-facebook display-2"></i>
                <%end%>
                </li>
                <li>
                <%=link_to 'https://line.me/ja/', class: 'nav-link text-light' do%>
                    <i class="fab fa-line display-2"></i>
                <%end%>
                </li>
            </ul>
            </div>
        </div>
    </div>
</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info p-1">
  <div class="container">
    <a class="navbar-brand text-light" href="/"><i class="fas fa-hotel"></i> <span>SapphireRooms</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-lavel="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto" style="flex-wrap: wrap;">
          <% if customer_signed_in? || admin_signed_in? %>
          <% unless admin_signed_in? %>
          <li>
            <%= link_to public_customer_path(current_customer), method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> ホーム
            <%end%>
          </li>
          <% else %>
          <li>
            <%= link_to root_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> ホーム
            <%end%>
          </li>
          <% end %>
          <li>
            <%= link_to public_customers_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-user-friends"></i> 会員一覧
            <%end%>
          </li>
          <li>
            <%= link_to public_books_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> ルーム
            <%end%>
          </li>
          <li>
            <%= link_to public_ratings_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-star"></i> レビュー
            <%end%>
          </li>
          <li>
            <%= link_to public_notifications_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-circle n-circle"></i> 通知
            <%end%>
          </li>
          <li>
            <%= link_to public_groups_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> グループ一覧
            <%end%>
          </li>
          <% if !admin_signed_in? %>
          <li>
            <%= link_to new_public_group_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-object-group"></i> グループ作成
            <%end%>
          </li>
          <% end %>
          <% if !admin_signed_in? && current_customer.name != "guestuser" %>
          <li>
            <%= link_to public_customer_unsubscribe_path(current_customer), method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-users-slash"></i> 退会する
            <%end%>
          </li>
          <%end%>
          <li>
            <%= link_to public_dictionaries_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-book"></i> 辞典
            <%end%>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <%end%>
          </li>

          <%else%>

          <li>
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> ホーム
            <%end%>
          </li>
          <li>
            <%= link_to public_home_about_path, class: 'nav-link text-light' do %>
              <i class="fas fa-store"></i> サイト紹介
            <%end%>
          </li>
          <li>
            <%= link_to public_dictionaries_path, method: :get, class: 'nav-link text-light' do %>
              <i class="fas fa-book"></i> 辞典
            <%end%>
          </li>
          <li>
            <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 会員登録
            <%end%>
          </li>
          <li>
            <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <%end%>
          </li>
          <li>
            <%= link_to customer_guest_sign_in_path, class: 'nav-link text-light', method: :post do %>
              <i class="fa fa-user"></i> ゲストログイン
             <% end %>
          </li>
          <li>
            <%= link_to new_admin_session_path, class: 'nav-link text-light', method: :get do %>
              <i class="fas fa-chess-king"></i> 管理者ログイン
            <% end %>
          </li>
          <%end%>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SapphireRooms</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="position: sticky; top: 0; z-index: 5;">
      <%= render 'layouts/header'%>
    </header>
    <main>
      <% if customer_signed_in? || admin_signed_in? %>
      <i id="notice" style="font-size: 20px; font-family: Georgia, serif;"><%= notice %></i>
      <div class="d-flex justify-content-center mb-2">
        <div class="mr-3 search"><%= render 'public/searches/form' %></div>
        <div class="mr-3 search"><%= render 'public/searches/tag_form' %></div>
      </div>
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer'%>
    </footer>
  </body>
</html>